PRODUCT_NAME = "PMD2"
PRODUCT_STRING = "ElmorLabs PMD2"
VENDOR_ID = 0xEE
PRODUCT_ID = 0x15
FIRMWARE_VERSION = 0x00
SENSOR_POWER_NUM = 10

SENSOR_DEVICES = [
    "ATX24",
    "12V",
    "5V",
    "3.3V",
    "HPWR1",
    "EPS1",
    "EPS2",
    "PCIE1",
    "PCIE2",
    "PCIE3",
]
